### PR TITLE
Fix #1 by adding RSS to the site

### LINKED ISSUE #1: RSS feed
Greetings,

My RSS feed reader can't find the feed for this blog.

Could you add this?

Just to make your life easier:
- [add the RSS feed to astro](https://docs.astro.build/en/guides/rss/)
- add it as a link in head:
```html
<link rel="alternate" type="application/rss+xml" title="Blog with astro" href="/rss/feed/url"/>
```

Thanks!

### PR DESCRIPTION
**Pull request by Andersos**
This pull request adds a RSS feed to the site according to https://docs.astro.build/en/guides/rss/
It also fixes issue #1. 

Let me know if you want any changes.

### CODE REVIEW

**Comment by pilcrowOnPaper** [comment]
lmao thanks

Can you change the js file into ts?

**Comment by Andersos** [comment]
I have changed it to `.ts` now. Thanks for pointing it out.

**Review by pilcrowOnPaper — APPROVED** [review]

**Comment by pilcrowOnPaper** [comment]
Thanks!

**Comment by Andersos** [comment]
No problem. I would like to read you blog and prefere to subscribe with rss. 

Thanks for sharing on your blog 😃

**Pull request merged**
